# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Thomas Michaeler Theme"
license = "MIT"
tags = []
features = []
min_version = 0.1

[author]
  name = "Thomas Michaeler"
  homepage = "https://thomasmichaeler.com/"

# If porting an existing theme
[original]